const Compliments: string[] = [
	'Meu dia começa pensando em você e termina com você em meus sonhos.',
	'Eu adoro como você se preocupa comigo.',
	'Com você, me sinto em casa.',
	'Eu adoro como posso ser eu mesmo quando estou com você.',
	'Desde que te conheci, acordo sorrindo todas as manhãs.',
	'Nunca, em meus sonhos mais loucos, imaginei que encontraria alguém como você.',
	'Sua foto está ao lado da palavra "perfeição" no dicionário.',
	'Eu sinto saudade de você antes mesmo de dar tchau.',
	'Queria que você se visse como eu te vejo!',
	'Eu irei te elogiar hoje, amanhã e sempre. Você não merece menos do que isso.',
	'A vida virou poesia quando você chegou.',
	'Seu sorriso é a maior prova de que as melhores coisas da vida são de graça.',
	'Ei, me ajuda aqui! Sua beleza me cegou momentaneamente.',
	'Você está maravilhosa. Como sempre.',
	'Como pode alguém ser tão linda e ainda mais bonita por dentro?',
	'Você fica ainda mais fofa quando ri.',
	'Você é maravilhosa sem fazer nenhum esforço.',
	'Não existe palavra no dicionário para definir o quão bonita você é.',
	'Você está bonita hoje. Assim como em todos os outros dias.',
	'Das pontas dos dedos dos pés ao último fio de cabelo, você é tão linda.',
	'Você é maravilhosa com M maiúsculo.',
	'O teu riso é apaixonante. ❤️',
	'Seu sorriso é tão contagiante que deveria vir com um aviso de risco de felicidade excessiva. 🥰',
	'Quando vejo você, sinto como se tivesse encontrado a resposta para a pergunta "qual é o sentido da vida?".',
	'Minha vontade é de te abraçar e nunca mais largar.',
	'Se você fosse uma música seria as melhores notas.',
	'Seu jeito meigo e delicado é como um bálsamo para minha alma. ',
	'Você é a pessoa mais bonita que já vi, tanto por fora quanto por dentro.',
	'A sua beleza é a paisagem mais linda que meus olhos já viram.',
	'Você me cativa. 🥰',
	'Não me leve a mal, mas você arrasa com o meu pobre coração! 💘',
	'Eu olho sua foto e fico hipnotizado pela sua beleza.',
	'Você é a mais perfeita poesia.',
	'Vou criar um filtro e colocar o seu nome. Você é perfeita!',
	'Ei, você, dona de uma beleza rara... Você arrasa com o meu coração.',
	'Esses olhos profundos e esse rosto fascinante: você é maravilhosa!',
	'A tua beleza me impressiona cada dia mais. ❤️',
	'Seus olhos são uma imensidão profunda que me fazem mergulhar em ti.',
	'Não há palavras que possam definir a sua beleza. Ela é única. ❤️',
	'Seus olhos cheios de brilho são fascinantes. 😍',
	'A magia mora ao seu lado. ✨',
	'Às vezes, eu me pergunto se você é real ou se eu estou sonhando.',
	'Se tudo for um sonho, por favor não me acorde! Prefiro continuar sonhando com você na minha vida.',
	'Com você, sinto-me em segurança. Sinto que posso confessar tudo, sinto que posso ser eu, sem qualquer medo. Obrigado.',
];

export default Compliments;
