const Compliments: string[] = [
	'Meu dia começa pensando em você e termina com você em meus sonhos.',
	'Eu adoro como você se preocupa comigo.',
	'Com você, me sinto em casa.',
	'Eu adoro como posso ser eu mesmo quando estou com você.',
	'Desde que te conheci, acordo sorrindo todas as manhãs.',
	'Nunca, em meus sonhos mais loucos, imaginei que encontraria alguém como você.',
	'Sua foto está ao lado da palavra "perfeição" no dicionário.',
	'Eu sinto saudade de você antes mesmo de dar tchau.',
	'Queria que você se visse como eu te vejo!',
	'Eu irei te elogiar hoje, amanhã e sempre. Você não merece menos do que isso.',
	'A vida virou poesia quando você chegou.',
	'Seu sorriso é a maior prova de que as melhores coisas da vida são de graça.',
	'Ei, me ajuda aqui! Sua beleza me cegou momentaneamente.',
	'Você está maravilhosa. Como sempre.',
	'Como pode alguém ser tão linda e ainda mais bonita por dentro?',
	'Você fica ainda mais fofa quando ri.',
	'Você é maravilhosa sem fazer nenhum esforço.',
	'Não existe palavra no dicionário para definir o quão bonita você é.',
	'Você está bonita hoje. Assim como em todos os outros dias.',
	'Das pontas dos dedos dos pés ao último fio de cabelo, você é tão linda.',
	'Você é maravilhosa com M maiúsculo.',
	'O teu riso é apaixonante. ❤️',
	'Seu sorriso é tão contagiante que deveria vir com um aviso de risco de felicidade excessiva. 🥰',
	'Quando vejo você, sinto como se tivesse encontrado a resposta para a pergunta "qual é o sentido da vida?".',
	'Minha vontade é de te abraçar e nunca mais largar.',
	'Se você fosse uma música seria as melhores notas.',
	'Seu jeito meigo e delicado é como um bálsamo para minha alma. ',
	'Você é a pessoa mais bonita que já vi, tanto por fora quanto por dentro.',
	'A sua beleza é a paisagem mais linda que meus olhos já viram.',
	'Você me cativa. 🥰',
	'Não me leve a mal, mas você arrasa com o meu pobre coração! 💘',
	'Eu olho sua foto e fico hipnotizado pela sua beleza.',
	'Você é a mais perfeita poesia.',
	'Vou criar um filtro e colocar o seu nome. Você é perfeita!',
	'Ei, você, dona de uma beleza rara... Você arrasa com o meu coração.',
	'Esses olhos profundos e esse rosto fascinante: você é maravilhosa!',
	'A tua beleza me impressiona cada dia mais. ❤️',
	'Seus olhos são uma imensidão profunda que me fazem mergulhar em ti.',
	'Não há palavras que possam definir a sua beleza. Ela é única. ❤️',
	'Seus olhos cheios de brilho são fascinantes. 😍',
	'A magia mora ao seu lado. ✨',
	'Às vezes, eu me pergunto se você é real ou se eu estou sonhando.',
	'Se tudo for um sonho, por favor não me acorde! Prefiro continuar sonhando com você na minha vida.',
	'Com você, sinto-me em segurança. Sinto que posso confessar tudo, sinto que posso ser eu, sem qualquer medo. Obrigado.',
	'Você ilumina qualquer lugar com seu sorriso.',
	'Sua gentileza é contagiante.',
	'Seu amor torna cada dia especial.',
	'Você é a razão pela qual meu coração bate mais rápido.',
	'Sua beleza interior é tão radiante quanto sua beleza exterior.',
	'Cada momento ao seu lado é um presente.',
	'Sua inteligência é inspiradora.',
	'Sua positividade é como um raio de sol em dias nublados.',
	'Seu toque é aconchegante e reconfortante.',
	'Sua determinação é admirável.',
	'Você é o meu porto seguro.',
	'Seu carinho faz tudo valer a pena.',
	'Sua compaixão faz do mundo um lugar melhor.',
	'Seus olhos refletem a pureza da sua alma.',
	'Sua presença transforma qualquer dia comum em extraordinário.',
	'Você é a musa da minha vida.',
	'Sua paciência é um exemplo a ser seguido.',
	'Cada momento ao seu lado é inesquecível.',
	'Você é a razão pela qual eu acredito no amor verdadeiro.',
	'Seu sorriso ilumina até os dias mais sombrios.',
	'Sua força interior é inspiradora.',
	'Cada detalhe sobre você é simplesmente encantador.',
	'Seu senso de humor torna tudo mais leve.',
	'Sua voz é a melodia que embala meus sonhos.',
	'Seu abraço é o melhor lugar do mundo.',
	'Você é a melhor parte do meu dia.',
	'Sua presença é como um abraço para minha alma.',
	'Sua generosidade é incomparável.',
	'Sua doçura é como um doce para minha alma.',
	'Você é a definição de beleza e graça.',
	'Seu amor é o maior presente que já recebi.',
	'Sua sabedoria me guia em momentos de dúvida.',
	'Seu apoio é meu maior impulso.',
	'Sua autenticidade é cativante.',
	'Seu riso é a trilha sonora da minha felicidade.',
	'Cada dia ao seu lado é uma bênção.',
	'Seu toque suave acalma até a tempestade mais forte.',
	'Você é a inspiração por trás dos meus sonhos.',
	'Sua presença faz o mundo parecer mais bonito.',
	'Seu amor é a luz que guia meu caminho.',
	'Sua determinação é como uma chama que nunca se apaga.',
	'Seu coração é o lugar onde eu pertenço.',
	'Sua bondade é um exemplo para todos ao seu redor.',
	'Você é a resposta para todas as minhas preces.',
	'Sua presença é o maior presente que já recebi.',
	'Seu sorriso é o motivo da minha felicidade.',
	'Sua humildade é inspiradora.',
	'Você é a razão pela qual a vida é tão bela.',
	'Seu sorriso é o raio de sol que ilumina meu dia.',
	'Sua presença é como um raio de sol em dias chuvosos.',
	'Seu amor é o presente mais valioso que já recebi.',
	'Seu carinho é o que me faz sentir amado.',
	'Sua presença é o lar que eu sempre quis.',
	'Seu toque é a poesia que meu coração recita.',
	'Você é a razão pela qual a vida é tão colorida.',
	'Sua determinação é como um farol na escuridão.',
	'Seu sorriso é a luz no fim do túnel.',
	'Sua força interior é um exemplo para todos.',
	'Seu amor é o alicerce da minha felicidade.',
	'Sua sabedoria é um guia valioso.',
	'Seu abraço é o refúgio perfeito.',
	'Sua compaixão faz do mundo um lugar mais gentil.',
	'Você é a razão pela qual acredito no amor eterno.',
	'Seu sorriso é o raio de sol que ilumina meu dia.',
	'Sua presença é como um bálsamo para minha alma.',
	'Seu toque é a melodia que embala meu coração.',
	'Sua alegria é contagiante.',
	'Seu amor é a força que impulsiona minha vida.',
	'Sua paciência é um tesouro raro.',
	'Você é a musa que inspira minhas criações.',
	'Seu sorriso é a obra-prima da felicidade.',
	'Sua gentileza é como uma brisa suave.',
	'Seu amor é a razão pela qual o mundo é tão bonito.',
	'Sua presença é a magia que transforma meu dia.',
	'Seu abraço é o conforto que eu sempre procuro.',
	'Você é a estrela que ilumina meu céu escuro.',
	'Sua compreensão torna tudo mais fácil.',
	'Sua empatia toca meu coração profundamente.',
	'Cada dia ao seu lado é uma aventura maravilhosa.',
	'Sua presença é como um raio de sol em dias chuvosos.',
	'Seu amor é o melhor presente que já recebi.',
	'Seu sorriso é a jóia mais preciosa.',
	'Sua paciência é um tesouro que eu guardo com carinho.',
	'Seu amor é o fogo que aquece meu coração.',
	'Sua presença é o presente mais valioso.',
	'Seu sorriso é a luz que guia meu caminho.',
	'Sua bondade é como um farol na escuridão.',
	'Seu amor é a música que embala minha existência.',
	'Sua paciência é uma virtude que admiro.',
	'Você é a razão pela qual acredito na magia do amor.',
	'Sua compreensão é o conforto que eu sempre procurei.',
	'Seu sorriso é a pintura mais bonita da minha vida.',
	'Sua força interior é um exemplo de coragem.',
	'Seu amor é o tesouro que eu sempre quis encontrar.',
	'Sua presença é a razão pela qual meu coração sorri.',
	'Sua paciência é um tesouro que valorizo mais do que palavras podem expressar.',
	'Seu sorriso é a razão pela qual meu dia é sempre especial.',
	'Sua compreensão é o alicerce da nossa relação duradoura.',
	'Seu toque é a ternura que me faz sentir amado.',
	'Você é a razão pela qual eu acredito na beleza do amor.',
	'Sua paciência é uma qualidade rara que eu admiro profundamente.',
	'Seu amor é a força que me impulsiona a ser melhor a cada dia.',
	'Sua presença é um presente que enche minha vida de alegria.',
	'Seu sorriso é a luz que ilumina os dias mais nublados.',
	'Sua bondade é como uma brisa suave que acalma minha mente.',
	'Seu amor é a melodia que embala meus sonhos todas as noites.',
	'Sua paciência é um presente precioso que eu nunca subestimo.',
	'Seu sorriso é a razão pela qual meu dia é sempre especial.',
	'Sua compreensão é o alicerce da nossa relação duradoura.',
	'Seu toque é a ternura que me faz sentir amado.',
	'Você é a razão pela qual eu acredito na beleza do amor.',
	'Sua paciência é uma virtude que faz nosso relacionamento ainda mais especial.',
	'Seu amor é a força que me impulsiona a alcançar o melhor de mim mesmo.',
	'Sua presença é um presente que enche minha vida de alegria e gratidão.',
	'Seu sorriso é a luz que ilumina os dias mais nublados.',
	'Sua bondade é como uma brisa suave que acalma minha alma inquieta.',
	'Seu amor é a melodia que embala meu coração todos os dias.',
	'Sua paciência é um presente valioso que eu nunca subestimo.',
	'Seu sorriso é a razão pela qual meu dia é sempre especial.',
	'Sua compreensão é o alicerce da nossa relação duradoura.',
	'Seu toque é a ternura que me faz sentir amado.',
	'Você é a razão pela qual eu acredito na beleza do amor.',
	'Sua paciência é uma qualidade rara que eu admiro profundamente.',
	'Seu amor é a força que me impulsiona a ser melhor a cada dia.',
	'Sua presença é o presente mais valioso que já recebi na vida.',
	'Seu sorriso é a luz que ilumina os dias mais nublados.',
	'Sua bondade é como um bálsamo que cura qualquer ferida.',
	'Seu amor é a inspiração por trás dos meus melhores momentos.',
	'Sua paciência é um tesouro que valorizo mais do que palavras podem expressar.',
	'Seu sorriso é a razão pela qual meu coração bate mais rápido.',
];

export default Compliments;
